# Generated by Django 6.0.1 on 2026-02-07 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='data_upload',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
