# Generated by Django 6.0.1 on 2026-02-07 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_documentos_data_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentos',
            name='data_upload',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
